name: pytest

on:
  push:
    paths:
      - '.github/workflows/pytest.yml'
      - '**/requirements.txt'
      - '**.py'
  pull_request:
    paths:
      - '.github/workflows/pytest.yml'
      - '**/requirements.txt'
      - '**.py'

jobs:
  test:

    strategy:
      matrix:
        python: ['3.7', '3.8']

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python }}

    # Cache pip dependencies
    # See also: https://github.com/actions/cache/blob/main/examples.md#python---pip
    - name: Get pip cache dir
      id: pip-cache
      run: |
        echo "::set-output name=dir::$(pip cache dir)"

    - name: pip cache
      uses: actions/cache@v2
      with:
        path: ${{ steps.pip-cache.outputs.dir }}
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        # install boorukits as editable package
        pip install -e .

    - name: Lint with flake8
      run: |
        flake8 . --count --show-source --statistics

    - name: Test with pytest
      env:
        PYTHONPATH: '.:./src'
      run: |
        pytest
